### ISSUE TITLE
Display Names for models

### ISSUE THREAD

**Issue by davidbuckhurst** [bbc/hive_mind#113]
I want to be able to identify things like G920F as Galaxy S6

**Comment by jrmhaig** [comment]
Create a gem similar to https://rubygems.org/gems/ios-devices/versions/0.2.1

**Comment by jonpwilson** [comment]
There's a spreadsheet on the [play store](https://support.google.com/googleplay/answer/1727131) that contains all of the known Android device information. We should parse the CSV and a lookup based on that information

**Comment by jonpwilson** [comment]
Created a project [here](https://github.com/bbc/android-devices) for this

**Comment by jonpwilson** [comment]
The android-devices gem has been released: bbc/android-devices#1
